import { prefixLink } from 'gatsby-helpers'; // eslint-disable-line
import GraphQLLogo from '../images/graphql.png';

export default [
  {
    title: 'The fastest way to get started with GraphQL.',
    author: 'Michael Paris',
    url: prefixLink('/blog/2016-06-14-fastest-way-to-get-started/'),
    description: 'First things first: GraphQL is awesome. If you’re not already building on it, right now is a great time to start! As a quick introduction, GraphQL is an application layer query language designed by Facebook that is used to power many of their web and mobile applications.',
    createdAt: '2016-06-14 14:23:37 -0700',
    tags: ['GraphQL', 'Tutorial'],
  },
  {
    title: 'Learn GraphQL',
    author: 'Kadira',
    url: 'https://learngraphql.com/',
    description: 'Learn GraphQL with an hour-long guide that will walk you through how GraphQL fits into your architecture, creating a schema, and executing queries.',
    createdAt: '2015-06-01 00:00:00 -0700',
    tags: ['GraphQL', 'Tutorial'],
    img: GraphQLLogo,
  },
  {
    title: 'Social Authentication with OAuth + GraphQL',
    author: 'Vince Ning',
    url: prefixLink('/blog/2016-06-28-social-auth-graphql/'),
    description: 'Quick guide on how to use OAuth with Scaphold\'s GraphQL platform. Social authentication has been a hot topic for developers and users alike. There are many guides on how to implement it for traditional REST-based APIs, so here’s one for the good guys.',
    createdAt: '2016-06-28 14:23:37 -0700',
    tags: ['GraphQL', 'OAuth'],
  },
  {
    title: 'Pokémon Go and GraphQL with AWS Lambda',
    author: 'Vince Ning',
    url: prefixLink('/blog/2016-07-14-2016-07-14-pokemon-go-graphql-with-aws-lambda/'),
    description: 'Quick guide on how to notify the nearest Pokémon Trainer with event-based triggers on Scaphold’s GraphQL platform. Want to get notified every time a new rare Pokémon appears near you in Pokémon Go? Excited to have them join you in the ultimate nostalgia-filled quest to catch them all? Here’s a simple way to get started with GraphQL!',
    createdAt: '2016-07-14 14:23:37 -0700',
    tags: ['GraphQL', 'Pokémon', 'Lambda'],
  },
  {
    title: 'Build a Payments API with Stripe and GraphQL',
    author: 'Michael Paris',
    url: prefixLink('/blog/2016-07-17-payments-api-with-graphql/'),
    description: 'Today we are going to design, build, and deploy a website into production. Even better, we are going to do it using GraphQL, Angular JS 2.0, Apollo Client, and Scaphold.io. Forget the “Hello, world” tutorial, we’re going to build the “Save the world” tutorial. Check out the final product at https://give.scaphold.io/!',
    createdAt: '2016-07-17 12:00:00 -0700',
    tags: ['GraphQL', 'Stripe', 'Donation'],
  },
  {
    title: 'Build Better Websites with Angular2 and GraphQL',
    author: 'Michael Paris',
    url: prefixLink('/blog/2016-07-21-build-better-websites-with-angular2-and-graphql/'),
    description: 'GraphQL is the best way to build modern applications. To prove it, let\'s build a production GraphQL powered application with Angular2, Apollo Client, and Webpack.',
    createdAt: '2016-07-21 11:59:00 -0700',
    tags: ['GraphQL', 'Angular2', 'Apollo'],
  },
  {
    title: 'How to Build Realtime Apps with GraphQL Subscriptions',
    author: 'Michael Paris',
    url: prefixLink('/blog/2016-11-10-build-realtime-apps-with-subs/'),
    description: 'When Facebook open-sourced GraphQL, they described how applications can perform reads with queries, and writes with mutations. However, often times clients want to get pushed updates from the server when data they care about changes. Enter GraphQL Subscriptions. Subscriptions make real-time functionality a first class citizen in GraphQL!',
    createdAt: '2016-11-10 00:00:00 -0700',
    tags: ['GraphQL', 'Subscriptions', 'Real-Time'],
  },
  {
    title: 'Apollo: How Scaphold Works!',
    author: 'Apollo GraphQL',
    url: 'https://www.youtube.com/watch?v=U2NKoStGBvE',
    description: 'Scaphold.io founders Michael Paris and Vincent Ning present at our GraphQL in Production meetup on 8/25/16 in San Francisco at Meteor Development Group.',
    createdAt: '2016-08-25 00:00:00 -0700',
    tags: ['GraphQL', 'Apollo', 'Scaphold', 'Tech Talk'],
  },
  {
    title: 'The Official GraphQL Site',
    author: 'Facebook',
    url: 'http://graphql.org/',
    description: 'GraphQL is a query language for APIs and a runtime for fulfilling those queries with your existing data. GraphQL provides a complete and understandable description of the data in your API, gives clients the power to ask for exactly what they need and nothing more, makes it easier to evolve APIs over time, and enables powerful developer tools.',
    createdAt: '2015-01-01 00:00:00 -0700',
    tags: ['GraphQL', 'Facebook'],
  },
  {
    title: 'Apollo Client: A flexible fully-featured GraphQL client for every platform',
    author: 'Meteor',
    url: 'http://dev.apollodata.com/',
    description: 'Apollo Client can be used in any JavaScript frontend where you want to use data from a GraphQL server. It\'s incrementally adoptable, universally compatible, simple to get started with, inspectable and understandable, built for interactive apps, small and flexible, and community-driven.',
    createdAt: '2016-02-21 00:00:00 -0700',
    tags: ['GraphQL', 'Apollo'],
  },
  {
    title: 'Relay: The Official Site',
    author: 'Facebook',
    url: 'https://facebook.github.io/relay/',
    description: 'A JavaScript framework for building data-driven React applications',
    createdAt: '2015-01-01 00:00:00 -0700',
    tags: ['GraphQL', 'Facebook', 'Relay'],
  },
  {
    title: 'Software Engineering Daily: Building Scalable GraphQL APIs',
    author: 'Jeff Meyerson',
    url: 'https://www.youtube.com/watch?v=U2NKoStGBvE',
    description: 'Scaphold.io provides GraphQL as a service, and today’s guests are the creators of Scaphold, Vince Ning and Michael Paris. Scaphold.io lets developers configure their schema, and hosts their data. Vince and Michael explain the basics of GraphQL, and also discuss how they are building a GraphQL as a service platform.',
    createdAt: '2016-08-08 00:00:00 -0700',
    tags: ['GraphQL', 'Software', 'Podcast'],
  },
];
